spring.application.name=osahaneat
spring.datasource.url=jdbc:mysql://localhost:3306/osahaneat

spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
jwt.privateKey=8TuhojHlqAX0rFffhhM6RMkahMB9AUiWZnk76c3Xt0M
fileUpload.rootPath=/Users/maianhtrung/MyDrive/JavaBackend/spring/uploads
